from app.database import Base
from app.models.entities import (
    Aluno,
    AplicacaoQuestionario,
    Avatar,
    Categoria,
    Escola,
    EscolaUser,
    OpcaoResposta,
    PersonalAccessToken,
    Pergunta,
    ProfessorTurma,
    Questionario,
    RegraClassificacao,
    Resposta,
    Resultado,
    Serie,
    Subcategoria,
    TermoAceite,
    Turma,
    User,
)

__all__ = [
    "Base",
    "Escola",
    "User",
    "EscolaUser",
    "Serie",
    "Turma",
    "Aluno",
    "Questionario",
    "Categoria",
    "Subcategoria",
    "Pergunta",
    "ProfessorTurma",
    "OpcaoResposta",
    "PersonalAccessToken",
    "RegraClassificacao",
    "AplicacaoQuestionario",
    "Resposta",
    "Resultado",
    "Avatar",
    "TermoAceite",
]
